language: go

go:
  - 1.9.x
  - "1.10"

stages:
  - lint
  - test
  - cover
  - build

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: cover
      script: make coverage
    - stage: test
      script: make test
    - stage: build
      script: make build
    - stage: run
      script: make run

matrix:
  allow_failures:
    - go: master
  fast_finish: true
